project:
  type: website
  execute-dir: project
  render: # Add HERE new chapters (but not the interactive qmd files)
    - index.qmd
    - chapters/coordination.qmd
    - chapters/communication.qmd
    - chapters/aiml_lab.qmd

website:
  page-navigation: true
  title: "AIML4OS"
  # In the two URLs below:
  # - replace AIML4OS by the Github account/organization your repository is hosted by;
  # - replace AIML4OS-template-quarto-r by the name of your repository.
  # If your repo is on the AIML4OS organization, change only the name of the repo.  
  site-url: "https://brendanjodowd.github.io/aiml4os_new"
  repo-url: "https://github.com/brendanjodowd/aiml4os_new"
  repo-actions: [edit, source, issue]
  # favicon: images/Template2.png
  sidebar:

    # Brendan commenting out these two lines, as they 
    # don't appear in the WP10 yaml

    # logo: resources/profile/main3.png
    # style: "docked"
    search: true
    contents: # Add HERE new chapters (but not the interactive qmd files)
      - href: index.qmd
        text: Homepage
      - href: chapters/coordination.qmd
        text: Project Management & Coordination
      - href: chapters/communication.qmd
        text: Communication
      - href: chapters/aiml_lab.qmd
        text: AI/ML Lab

format:
  html:
    theme:
      - cosmo
      # - brand
      # removing this line as it doesn't appear in the one for WP10
    css: styles.css
    toc: true

filters:
  - export-metadata.lua

